language: csharp
solution: ./src/CacheMagic.sln
install:
  - nuget restore ./src/CacheMagic.sln
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ./src/CacheMagic.sln
  - mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.clr4.exe ./src/CacheMagic.UnitTests/bin/Release/CacheMagic.UnitTests.dll